version: '3.8'

services:
  web:
    image: luandos/flask-docker-swarm-load-balancing:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: any
    ports:
      - "5000:5000"
    
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf